name: E2E Testing
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
#       - name: Run CRA Build
#         run: yarn build
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: cypress/build
  e2e_tests:
    runs-on: ubuntu-latest
    needs: install
    container: cypress/browsers:node14.17.0-chrome91-ff89
    strategy:
      fail-fast: false
      matrix:
        containers: [Home,Login]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: cypress/build
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
#           command: npm run test
          spec: cypress/integration/**/${{ matrix.containers }}.feature
          browser: chrome
          working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  report:
    runs-on: ubuntu-latest
    # needs: e2e_tests
    steps:
      - name: Save failed logs
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: failed-logs
          PUBLISH_DIR: cypress/logs
          keep_files: true
      - name: Generate HTML report
        run: node cucumber-html-report.js
      - name: Deploy HTML Report To GH Page
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: html-report
          PUBLISH_DIR: cypress/reports
          keep_files: true
